#!/usr/bin/env python
"""Analyze distance-binned recall and visualize far-range missed objects.

This script is intentionally post-hoc: run inference first with tools/test.py
and ``--out result.pkl``, then analyze that result file against the validation
annotations. It does not change training or evaluation behavior.
"""
import argparse
import csv
import importlib
import math
import os
from pathlib import Path

import mmcv
import numpy as np
import torch
from mmcv import Config
from mmdet3d.datasets import build_dataset


NUSCENES_CLASSES = [
    'car', 'truck', 'construction_vehicle', 'bus', 'trailer', 'barrier',
    'motorcycle', 'bicycle', 'pedestrian', 'traffic_cone'
]


def parse_args():
    parser = argparse.ArgumentParser(
        'Distance-binned recall and far-object miss visualization')
    parser.add_argument('config')
    parser.add_argument('result_pkl', help='Result pkl generated by tools/test.py --out')
    parser.add_argument('--out-dir', default='work_dirs/far_range_recall')
    parser.add_argument('--data-root', default=os.environ.get('NUSCENES_DATA_ROOT'))
    parser.add_argument('--ann-file', default=None)
    parser.add_argument('--score-thr', type=float, default=0.1)
    parser.add_argument('--match-dist', type=float, default=2.0,
                        help='Same-class center-distance threshold in meters.')
    parser.add_argument('--distance-bins', type=float, nargs='+',
                        default=[0.0, 30.0, 50.0, 80.0],
                        help='Distance bin edges in meters. Last bin is open-ended.')
    parser.add_argument('--vis-min-dist', type=float, default=30.0)
    parser.add_argument('--max-vis', type=int, default=80)
    return parser.parse_args()


def import_plugins(cfg, config_path):
    if not getattr(cfg, 'plugin', False):
        return
    plugin_dir = cfg.get('plugin_dir', None)
    if plugin_dir is None:
        module_path = '.'.join(Path(config_path).parent.parts)
    else:
        module_path = plugin_dir.rstrip('/').replace('/', '.')
    importlib.import_module(module_path)


def build_eval_dataset(cfg, args):
    import_plugins(cfg, args.config)
    data_cfg = cfg.data.val.copy()
    data_cfg.test_mode = True
    if args.data_root:
        data_cfg.data_root = args.data_root
    if args.ann_file:
        data_cfg.ann_file = args.ann_file
    elif args.data_root and isinstance(data_cfg.get('ann_file'), str):
        ann = data_cfg.ann_file
        if ann.startswith('./data/nuscenes/'):
            data_cfg.ann_file = os.path.join(args.data_root, ann[len('./data/nuscenes/'):])
    if hasattr(cfg, 'test_pipeline'):
        data_cfg.pipeline = cfg.test_pipeline
    return build_dataset(data_cfg)


def tensor_to_numpy(x):
    if x is None:
        return None
    if hasattr(x, 'tensor'):
        x = x.tensor
    if isinstance(x, torch.Tensor):
        return x.detach().cpu().numpy()
    return np.asarray(x)


def centers_from_boxes(boxes):
    if boxes is None:
        return np.zeros((0, 3), dtype=np.float32)
    if hasattr(boxes, 'gravity_center'):
        centers = boxes.gravity_center
        return tensor_to_numpy(centers)
    arr = tensor_to_numpy(boxes)
    return arr[:, :3] if arr.size else arr.reshape(0, 3)


def boxes_to_numpy(boxes):
    if boxes is None:
        return np.zeros((0, 7), dtype=np.float32)
    if hasattr(boxes, 'tensor'):
        return tensor_to_numpy(boxes.tensor)
    return tensor_to_numpy(boxes)


def unpack_prediction(result):
    if isinstance(result, dict) and 'pts_bbox' in result:
        result = result['pts_bbox']
    boxes = result.get('boxes_3d', result.get('boxes', None))
    scores = tensor_to_numpy(result.get('scores_3d', result.get('scores', None)))
    labels = tensor_to_numpy(result.get('labels_3d', result.get('labels', None)))
    if scores is None:
        scores = np.zeros((0,), dtype=np.float32)
    if labels is None:
        labels = np.zeros((0,), dtype=np.int64)
    return boxes, scores, labels.astype(np.int64)


def bin_label(distance, edges):
    for start, end in zip(edges[:-1], edges[1:]):
        if start <= distance < end:
            return f'{start:g}-{end:g}m'
    return f'>={edges[-1]:g}m'


def update_counter(summary, cls_name, dist_bin, matched):
    key = (dist_bin, cls_name)
    if key not in summary:
        summary[key] = {'gt': 0, 'tp': 0, 'fn': 0}
    summary[key]['gt'] += 1
    if matched:
        summary[key]['tp'] += 1
    else:
        summary[key]['fn'] += 1


def oriented_box_xy(box):
    if box is None or len(box) < 7:
        return None
    x, y, _, dx, dy, _, yaw = box[:7]
    c, s = math.cos(yaw), math.sin(yaw)
    corners = np.array([
        [dx / 2, dy / 2], [dx / 2, -dy / 2],
        [-dx / 2, -dy / 2], [-dx / 2, dy / 2], [dx / 2, dy / 2]
    ], dtype=np.float32)
    rot = np.array([[c, -s], [s, c]], dtype=np.float32)
    return corners @ rot.T + np.array([x, y], dtype=np.float32)


def draw_bev(sample_idx, gt_boxes, gt_labels, pred_boxes, pred_labels, pred_scores,
             missed_indices, class_names, out_path, score_thr):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_aspect('equal', adjustable='box')
    ax.set_xlim(-60, 60)
    ax.set_ylim(-60, 60)
    ax.grid(True, linewidth=0.4, alpha=0.35)
    ax.scatter([0], [0], c='black', s=16, label='ego')

    for i, box in enumerate(gt_boxes):
        poly = oriented_box_xy(box)
        color = 'tab:red' if i in missed_indices else 'tab:blue'
        lw = 2.2 if i in missed_indices else 1.0
        if poly is not None:
            ax.plot(poly[:, 0], poly[:, 1], color=color, linewidth=lw)
        ax.text(box[0], box[1], class_names[int(gt_labels[i])], color=color, fontsize=7)

    if pred_boxes is not None:
        for box, label, score in zip(pred_boxes, pred_labels, pred_scores):
            if score < score_thr:
                continue
            poly = oriented_box_xy(box)
            if poly is not None:
                ax.plot(poly[:, 0], poly[:, 1], color='tab:green', linewidth=0.8, alpha=0.75)
            ax.text(box[0], box[1], f'{class_names[int(label)]}:{score:.2f}',
                    color='tab:green', fontsize=6, alpha=0.75)

    ax.set_title(f'sample {sample_idx}: red GT = far missed objects')
    ax.set_xlabel('x / m')
    ax.set_ylabel('y / m')
    fig.tight_layout()
    fig.savefig(out_path, dpi=160)
    plt.close(fig)


def main():
    args = parse_args()
    out_dir = Path(args.out_dir)
    vis_dir = out_dir / 'vis'
    out_dir.mkdir(parents=True, exist_ok=True)
    vis_dir.mkdir(parents=True, exist_ok=True)

    cfg = Config.fromfile(args.config)
    dataset = build_eval_dataset(cfg, args)
    results = mmcv.load(args.result_pkl)
    if len(results) != len(dataset):
        raise ValueError(f'results length {len(results)} != dataset length {len(dataset)}')

    class_names = list(getattr(dataset, 'CLASSES', NUSCENES_CLASSES))
    edges = sorted(args.distance_bins)
    summary = {}
    sample_rows = []
    vis_count = 0

    for idx, result in enumerate(mmcv.track_iter_progress(results)):
        ann = dataset.get_ann_info(idx)
        gt_boxes_obj = ann['gt_bboxes_3d']
        gt_labels = tensor_to_numpy(ann['gt_labels_3d']).astype(np.int64)
        gt_centers = centers_from_boxes(gt_boxes_obj)
        gt_boxes = boxes_to_numpy(gt_boxes_obj)

        pred_boxes_obj, pred_scores, pred_labels = unpack_prediction(result)
        pred_centers = centers_from_boxes(pred_boxes_obj)
        pred_boxes = boxes_to_numpy(pred_boxes_obj)
        if pred_scores is None or pred_labels is None:
            pred_scores = np.zeros((0,), dtype=np.float32)
            pred_labels = np.zeros((0,), dtype=np.int64)
            pred_centers = np.zeros((0, 3), dtype=np.float32)
            pred_boxes = np.zeros((0, 7), dtype=np.float32)

        keep = pred_scores >= args.score_thr
        pred_scores = pred_scores[keep]
        pred_labels = pred_labels[keep]
        pred_centers = pred_centers[keep]
        pred_boxes = pred_boxes[keep] if pred_boxes is not None else None

        used_pred = np.zeros(len(pred_scores), dtype=bool)
        missed_far = []
        for gt_i, (gt_center, gt_label) in enumerate(zip(gt_centers, gt_labels)):
            dist = float(np.linalg.norm(gt_center[:2]))
            cls_name = class_names[int(gt_label)]
            candidates = np.where((pred_labels == gt_label) & (~used_pred))[0]
            matched = False
            best_pred = -1
            best_dist = float('inf')
            if len(candidates) > 0:
                center_dists = np.linalg.norm(pred_centers[candidates, :2] - gt_center[:2], axis=1)
                min_i = int(np.argmin(center_dists))
                best_dist = float(center_dists[min_i])
                best_pred = int(candidates[min_i])
                matched = best_dist <= args.match_dist
                if matched:
                    used_pred[best_pred] = True

            d_bin = bin_label(dist, edges)
            update_counter(summary, cls_name, d_bin, matched)
            sample_rows.append({
                'sample_idx': idx,
                'class': cls_name,
                'distance': f'{dist:.3f}',
                'distance_bin': d_bin,
                'matched': int(matched),
                'best_center_dist': f'{best_dist:.3f}' if best_pred >= 0 else '',
            })
            if (not matched) and dist >= args.vis_min_dist:
                missed_far.append(gt_i)

        if missed_far and vis_count < args.max_vis:
            draw_bev(
                idx, gt_boxes, gt_labels, pred_boxes, pred_labels, pred_scores,
                missed_far, class_names, vis_dir / f'sample_{idx:06d}_far_miss.png',
                args.score_thr)
            vis_count += 1

    summary_rows = []
    for (d_bin, cls_name), stats in sorted(summary.items()):
        recall = stats['tp'] / stats['gt'] if stats['gt'] > 0 else 0.0
        summary_rows.append({
            'distance_bin': d_bin,
            'class': cls_name,
            'gt': stats['gt'],
            'tp': stats['tp'],
            'fn': stats['fn'],
            'recall': f'{recall:.4f}',
        })

    with open(out_dir / 'distance_recall_summary.csv', 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['distance_bin', 'class', 'gt', 'tp', 'fn', 'recall'])
        writer.writeheader()
        writer.writerows(summary_rows)

    with open(out_dir / 'per_object_matches.csv', 'w', newline='') as f:
        writer = csv.DictWriter(
            f, fieldnames=['sample_idx', 'class', 'distance', 'distance_bin',
                           'matched', 'best_center_dist'])
        writer.writeheader()
        writer.writerows(sample_rows)

    total_gt = sum(int(r['gt']) for r in summary_rows)
    total_tp = sum(int(r['tp']) for r in summary_rows)
    total_fn = sum(int(r['fn']) for r in summary_rows)
    print('[done]')
    print(f'  output: {out_dir}')
    print(f'  gt/tp/fn: {total_gt}/{total_tp}/{total_fn}')
    print(f'  overall recall: {total_tp / total_gt if total_gt else 0.0:.4f}')
    print(f'  visualized far-miss samples: {vis_count}')


if __name__ == '__main__':
    main()
